### ISSUE TITLE
Add me in discord

### ISSUE THREAD

**Issue by tahnik** [vscera/cant-reach-you-tahnik#1]
Hey! Long time no see. My discord user ID: tboi#7375

**Comment by SirWindfield** [comment]
Has been too long, looks like everybody is working on new cool projects :smile:
Added you!

**Comment by tahnik** [comment]
Hm did not get an invite, maybe we are already friends in there. What's your discord name?

**Comment by SirWindfield** [comment]
same as here.

**Comment by tahnik** [comment]
Ah you're just offline. Cool. Just ping me when you're online
